#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_PATH="${1:-$ROOT_DIR/.run/ci/ui-screenshot.png}"
SCREENSHOT_PORT="${CI_SCREENSHOT_PORT:-18080}"
SCREENSHOT_USERNAME="${CI_SCREENSHOT_USERNAME:-gringorion}"
SCREENSHOT_PASSWORD="${CI_SCREENSHOT_PASSWORD:-ci-password}"
SCREENSHOT_FIXTURE_ENV="$ROOT_DIR/scripts/fixtures/screenshot-visual.env"
FORBIDDEN_VISIBLE_TEXT="${CI_SCREENSHOT_FORBIDDEN_VISIBLE_TEXT:-api key
access key
private key
ssh key
token
secret
password
password seed
ci-password
gringog
ci-user
nico
root
abc
codex
codex@enna.fr}"

mkdir -p "$(dirname "$OUTPUT_PATH")"

if [[ -f "$SCREENSHOT_FIXTURE_ENV" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$SCREENSHOT_FIXTURE_ENV"
  set +a
fi

if [[ -n "${CI_SCREENSHOT_CONTAINER_NAME:-}" ]]; then
  bash "$ROOT_DIR/scripts/seed-screenshot-data.sh" container "$CI_SCREENSHOT_CONTAINER_NAME"
fi

SCREENSHOT_MODE=local \
SCREENSHOT_URL="http://127.0.0.1:${SCREENSHOT_PORT}/" \
SCREENSHOT_USERNAME="$SCREENSHOT_USERNAME" \
SCREENSHOT_PASSWORD="$SCREENSHOT_PASSWORD" \
SCREENSHOT_EXPECTED_USER="$SCREENSHOT_USERNAME" \
SCREENSHOT_FORBIDDEN_VISIBLE_TEXT="$FORBIDDEN_VISIBLE_TEXT" \
SCREENSHOT_CONTROLLER_MODEL="${CI_SCREENSHOT_CONTROLLER_MODEL:-}" \
SCREENSHOT_STATUS_NETWORK="${CI_SCREENSHOT_STATUS_NETWORK:-}" \
SCREENSHOT_STATUS_SITE="${CI_SCREENSHOT_STATUS_SITE:-}" \
SCREENSHOT_STATUS_DEVICES="${CI_SCREENSHOT_STATUS_DEVICES:-}" \
SCREENSHOT_STATUS_CLIENTS="${CI_SCREENSHOT_STATUS_CLIENTS:-}" \
SCREENSHOT_REQUIRE_VERSION_FOOTER=true \
bash "$ROOT_DIR/scripts/update-screenshot.sh" "$OUTPUT_PATH"

ls -lh "$OUTPUT_PATH"
echo "OK: sanitized CI screenshot captured at $OUTPUT_PATH"
